source 'https://rubygems.org'

gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'faraday'
gem 'sinatra-cors', '~> 1.2'
gem 'concurrent-ruby', '~> 1.0', '>= 1.0.5'
gem 'sinatra-websocket', '~> 0.3.1'
